config/routes.rb
Rails.application.routes.draw do
  resources :offers
  resources :advertisers
  resources :administrators
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'
  get '/offers/change_state/:id', to: 'offers#change_state', as: 'change_offer_state'

  require 'sidekiq/web'

  mount Sidekiq::Web => '/sidekiq'

end

app/models/advertiser.rb
class Advertiser < ApplicationRecord
  has_many :offers, dependent: :destroy
  validates :name, presence: true, uniqueness: true
end

app/controllers/advertisers_controller.rb
class AdvertisersController < ApplicationController
  before_action :set_advertiser, only: [:show, :edit, :update, :destroy]

  # GET /advertisers
  # GET /advertisers.json
  def index
    @advertisers = Advertiser.all
  end

  # GET /advertisers/1
  # GET /advertisers/1.json
  def show
  end

  # GET /advertisers/new
  def new
    @advertiser = Advertiser.new
  end

  # GET /advertisers/1/edit
  def edit
  end

  # POST /advertisers
  # POST /advertisers.json
  def create
    @advertiser = Advertiser.new(advertiser_params)

    respond_to do |format|
      if @advertiser.save
        format.html { redirect_to @advertiser, notice: 'Advertiser was successfully created.' }
        format.json { render :show, status: :created, location: @advertiser }
      else
        format.html { render :new }
        format.json { render json: @advertiser.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /advertisers/1
  # PATCH/PUT /advertisers/1.json
  def update
    respond_to do |format|
      if @advertiser.update(advertiser_params)
        format.html { redirect_to @advertiser, notice: 'Advertiser was successfully updated.' }
        format.json { render :show, status: :ok, location: @advertiser }
      else
        format.html { render :edit }
        format.json { render json: @advertiser.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /advertisers/1
  # DELETE /advertisers/1.json
  def destroy
    @advertiser.destroy
    respond_to do |format|
      format.html { redirect_to advertisers_url, notice: 'Advertiser was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_advertiser
      @advertiser = Advertiser.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def advertiser_params
      params.require(:advertiser).permit(:name)
    end
end

app/helpers/advertisers_helper.rb
module AdvertisersHelper
end

app/views/advertisers/_form.html.erb
<%= form_for(@advertiser, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @advertiser.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@advertiser.errors.count, "error") %> prohibited this advertiser from being saved:</h4>

      <ul>
      <% @advertiser.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/advertisers/edit.html.erb
<div class="page-header">
  <%= link_to advertisers_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @advertiser, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing advertiser</h1>
</div>

<%= render 'form' %>

app/views/advertisers/index.html.erb
<div class="page-header">
  <%= link_to new_advertiser_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Advertiser
  <% end %>
  <h1>Listing Advertisers</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Name</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @advertisers) do |advertiser| %>
            <td><%= advertiser.name %></td>
            <td><%= link_to 'Show', advertiser %></td>
        <td><%= link_to 'Edit', edit_advertiser_path(advertiser) %></td>
        <td><%= link_to 'Destroy', advertiser, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/advertisers/new.html.erb
<div class="page-header">
  <%= link_to advertisers_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New advertiser</h1>
</div>

<%= render 'form' %>

app/views/advertisers/show.html.erb
<div class="page-header">
  <%= link_to advertisers_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_advertiser_path(@advertiser), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show advertiser</h1>
</div>

<dl class="dl-horizontal">
  <dt>Name:</dt>
  <dd><%= @advertiser.name %></dd>

</dl>