config/routes.rb
Rails.application.routes.draw do
  resources :offers
  resources :advertisers
  resources :administrators
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'
  get '/offers/change_state/:id', to: 'offers#change_state', as: 'change_offer_state'

  require 'sidekiq/web'

  mount Sidekiq::Web => '/sidekiq'

end

app/models/administrator.rb
class Administrator < ApplicationRecord
  validates :name, presence: true, uniqueness: true
end

app/controllers/administrators_controller.rb
class AdministratorsController < ApplicationController
  before_action :set_administrator, only: [:show, :edit, :update, :destroy]

  # GET /administrators
  # GET /administrators.json
  def index
    @administrators = Administrator.all
  end

  # GET /administrators/1
  # GET /administrators/1.json
  def show
  end

  # GET /administrators/new
  def new
    @administrator = Administrator.new
  end

  # GET /administrators/1/edit
  def edit
  end

  # POST /administrators
  # POST /administrators.json
  def create
    @administrator = Administrator.new(administrator_params)

    respond_to do |format|
      if @administrator.save
        format.html { redirect_to @administrator, notice: 'Administrator was successfully created.' }
        format.json { render :show, status: :created, location: @administrator }
      else
        format.html { render :new }
        format.json { render json: @administrator.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /administrators/1
  # PATCH/PUT /administrators/1.json
  def update
    respond_to do |format|
      if @administrator.update(administrator_params)
        format.html { redirect_to @administrator, notice: 'Administrator was successfully updated.' }
        format.json { render :show, status: :ok, location: @administrator }
      else
        format.html { render :edit }
        format.json { render json: @administrator.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /administrators/1
  # DELETE /administrators/1.json
  def destroy
    @administrator.destroy
    respond_to do |format|
      format.html { redirect_to administrators_url, notice: 'Administrator was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_administrator
      @administrator = Administrator.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def administrator_params
      params.require(:administrator).permit(:name, :email, :password)
    end
end

app/helpers/administrators_helper.rb
module AdministratorsHelper
end

app/views/administrators/_form.html.erb
<%= form_for(@administrator, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @administrator.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@administrator.errors.count, "error") %> prohibited this administrator from being saved:</h4>

      <ul>
      <% @administrator.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :email, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :email, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :password, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :password, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/administrators/edit.html.erb
<div class="page-header">
  <%= link_to administrators_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @administrator, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing administrator</h1>
</div>

<%= render 'form' %>

app/views/administrators/index.html.erb
<div class="page-header">
  <%= link_to new_administrator_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Administrator
  <% end %>
  <h1>Listing Administrators</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Name</th>
            <th>Email</th>
            <th>Password</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @administrators) do |administrator| %>
            <td><%= administrator.name %></td>
            <td><%= administrator.email %></td>
            <td><%= administrator.password %></td>
            <td><%= link_to 'Show', administrator %></td>
        <td><%= link_to 'Edit', edit_administrator_path(administrator) %></td>
        <td><%= link_to 'Destroy', administrator, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/administrators/new.html.erb
<div class="page-header">
  <%= link_to administrators_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New administrator</h1>
</div>

<%= render 'form' %>

app/views/administrators/show.html.erb
<div class="page-header">
  <%= link_to administrators_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_administrator_path(@administrator), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show administrator</h1>
</div>

<dl class="dl-horizontal">
  <dt>Name:</dt>
  <dd><%= @administrator.name %></dd>

  <dt>Email:</dt>
  <dd><%= @administrator.email %></dd>

  <dt>Password:</dt>
  <dd><%= @administrator.password %></dd>

</dl>