config/routes.rb
Rails.application.routes.draw do
  resources :offers
  resources :advertisers
  resources :administrators
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'
  get '/offers/change_state/:id', to: 'offers#change_state', as: 'change_offer_state'

  require 'sidekiq/web'

  mount Sidekiq::Web => '/sidekiq'

end

app/models/offer.rb
class Offer < ApplicationRecord
  belongs_to :advertiser
  validates :url, :description, :start_at, presence: true
  # validates :url, format: URI::regexp(%w[http https]),
  validates :url, presence: true, uniqueness: true
  validates :description, length: { minimum: 5, maximum: 500 }
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  before_action :set_offer, only: [:show, :edit, :update, :destroy]

  # GET /offers
  # GET /offers.json
  def change_state
    @offer = Offer.find(params[:id])
    #@offer = Offer.find(offer_id)
    new_state = set_state(@offer)

    if @offer.state != new_state
      @offer.state = new_state
      if @offer.save
        state = @offer.state ? 'enabled' : 'disabled'
        redirect_to offers_url, notice: "Offer was successfully #{state}"
        # SetEnableStateWorker.perform_at(@offer.start_at, @offer.id)
        # SetDisableStateWorker.perform_at(@offer.end_at, @offer.id)
      else
        redirect_to offers_url, notice: 'Offer was not updated.'
      end
    else
      redirect_to offers_url
    end

  end

  def index
    @offers = Offer.all
  end

  # GET /offers/1
  # GET /offers/1.json
  def show
  end

  # GET /offers/new
  def new
    @offer = Offer.new
  end

  # GET /offers/1/edit
  def edit
  end

  # POST /offers
  # POST /offers.json
  def create


    @offer = Offer.new(offer_params)
    @offer.state = false

    respond_to do |format|
      if @offer.save
        format.html { redirect_to offers_url, notice: 'Offer was successfully created.' }
        format.json { render :show, status: :created, location: @offer }

        # SetEnableStateWorker.perform_at(@offer.start_at, @offer.id)
        # SetDisableStateWorker.perform_at(@offer.end_at, @offer.id)

      else
        format.html { render :new }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /offers/1
  # PATCH/PUT /offers/1.json
  def update
    respond_to do |format|
      if @offer.update(offer_params)
        format.html { redirect_to offers_url, notice: 'Offer was successfully updated.' }
        format.json { render :show, status: :ok, location: @offer }
      else
        format.html { render :edit }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /offers/1
  # DELETE /offers/1.json
  def destroy
    @offer.destroy
    respond_to do |format|
      format.html { redirect_to offers_url, notice: 'Offer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_offer
      @offer = Offer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def offer_params
      params.require(:offer).permit(:advertiser_id, :url, :description, :start_at, :end_at, :premium, :state)
    end

    def set_state(offer)

      if !offer.state

        if Time.now >= offer.start_at && offer.end_at.blank?
          return true
        end

        if Time.now >= offer.start_at && Time.now < offer.end_at
          return true
        end

      else

        if !offer.end_at.blank?
          if Time.now <= offer.end_at
            return false
          end
        end

        return true

      end

    end

end

app/helpers/offers_helper.rb
module OffersHelper
end

app/views/offers/_form.html.erb
<%= form_for(@offer, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @offer.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@offer.errors.count, "error") %> prohibited this offer from being saved:</h4>

      <ul>
      <% @offer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :advertiser_id, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.select :advertiser_id, Advertiser.all.collect{|a| [a.name, a.id]}, {}, required:true, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :url, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :url, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :description, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_area :description, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :start_at, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.datetime_select :start_at, order: [ :day, :month, :year], class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :end_at, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.datetime_select :end_at, include_blank: true, order: [ :day, :month, :year], class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :premium, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.check_box :premium, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/offers/edit.html.erb
<div class="page-header">
  <%= link_to offers_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @offer, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing offer</h1>
</div>

<%= render 'form' %>

app/views/offers/index.html.erb
<div class="page-header">
  <%= link_to new_offer_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Offer
  <% end %>
  <h1>Listing Offers</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Advertiser</th>
            <th>Url</th>
            <th>Description</th>
            <th>Starts at</th>
            <th>Ends at</th>
            <th>Premium</th>
            <th>State</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @offers) do |offer| %>
            <td><%= offer.advertiser.name %></td>
            <td><%= offer.url %></td>
            <td><%= offer.description %></td>
            <td><%= offer.start_at %></td>
            <td><%= offer.end_at %></td>
            <td><%= offer.premium %></td>
            <td><%= offer.state ? 'enabled' : 'disabled' %></td>
        <td><%= link_to 'Edit', edit_offer_path(offer) %></td>
        <% button_state = !offer.state ? 'enable' : 'disable' %>
        <td><%= link_to "#{button_state}", change_offer_state_path(offer) %></td>
        <td><%= link_to 'Destroy', offer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/offers/new.html.erb
<div class="page-header">
  <%= link_to offers_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New offer</h1>
</div>

<%= render 'form' %>

app/views/offers/show.html.erb
<div class="page-header">
  <%= link_to offers_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_offer_path(@offer), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show offer</h1>
</div>

<dl class="dl-horizontal">

  <dt>Advertiser:</dt>
  <dd><%= @offer.advertiser.name %></dd>

  <dt>Url:</dt>
  <dd><%= @offer.url %></dd>

  <dt>Description:</dt>
  <dd><%= @offer.description %></dd>

  <dt>Start at:</dt>
  <dd><%= @offer.start_at %></dd>

  <dt>End at:</dt>
  <dd><%= @offer.end_at %></dd>

  <dt>Premium:</dt>
  <dd><%= @offer.premium %></dd>

  <dt>State:</dt>
  <dd><%= @offer.state %></dd>

</dl>